# Robinson et al (2021) "Inherited MUTYH mutations cause elevated somatic mutation rates and distinctive mutational signatures in normal human cells"

#############################
# CODE TO RECREATE FIGURE 3 #
#############################

#Fit signatures to observed counts
options(stringsAsFactors = F)
library(sigfit)
library(RColorBrewer)
library(ape)
library(ggtree)
data("cosmic_signatures_v2")
# Load data frame with mutation counts for each branch ofthe phyogenetic tree classified according to 96-channel trinucleotide.
all_counts=read.table("HDP_mutation_matrix_2021-05-11.txt",header=T)
# Load data frame with the mde noovo mutational signature exposure of each branch ofht e phylogenetic tree (generated by HDP de novo extraction)
hdp_exposures=read.table("HDP_exposures_2021-05-11.txt",header=T)
rownames(hdp_exposures)=hdp_exposures[,1]
hdp_exposures[,1] <- NULL
rownames(all_counts)=all_counts$Samples
all_counts$Samples <- NULL
rownames(final_sigs) = colnames(hdp_exposures)
hdp2ref=readRDS(paste0(filedir,"hdp2refsigs.Rdata"))
colnames(all_counts)=colnames(final_sigs)=colnames(cosmic_signatures_v2)
patients=c("PD44887", "PD44888", "PD44889", "PD44890", "PD44891", "PD50743","PD50744","PD50745","PD50746","PD50747")
nsigs <- length(unique(unlist(hdp2ref)))
sig_order=1:nsigs
names(sig_order)=c("SBS1","SBS5","SBS17b","SBS18","SBS36","SBS38","SBS88") # Reference signatures identified through deconvolution of de novo signature contirbution using expectatoin maximisation algorithm
all_cols <- colorRampPalette(brewer.pal(8, "Spectral"))(8)
names(all_cols)=names(sig_order)

#Reformat the order of the sigprofiler generated matrix
trinuc_pos_three <- rep(c("A","C","G","T"), times = 24)
trinuc_pos_two.2 <- rep(c("C","T"), each = 48)
trinuc_pos_two.1 <- rep(c("A","G", "T","A", "C", "G"), each = 16)
trinuc_pos_one <- rep(rep(c("A","C","G","T"), each = 4), times = 6)
neworder <-  as.factor(paste0(trinuc_pos_one,"[",trinuc_pos_two.2,">",trinuc_pos_two.1,"]",trinuc_pos_three))

# COSMIC Reference signatures 1:90 (accessed October 2020). 
# SBS36 has been replaced by HDP N1 which represents a purer signautre (less SBS1 and SBS5 contamination)
final_sigs_refrence_new <- read.table("sigs_used_treefit.txt",header=T)
plotsuffix="final"

# Loop through all patients to create one phylogenetic tree per patient
for(patient in patients){
  
  #Ascertain if the signature is present to any significant extent i.e >10% prevelance 
  hdp_sigs_present=colnames(hdp_exposures)[colSums(hdp_exposures[grepl(patient,rownames(hdp_exposures)),]>0.1)>0]
  ref_sigs_present=unique(c(unlist(hdp2ref[hdp_sigs_present]),"SBS1","SBS5"))
  print(paste0(patient, " ", ref_sigs_present))
  
  #Retrieve mutation counts per patient per branch
  counts_patient=all_counts[grepl(patient,rownames(all_counts)),]
  colnames(counts_patient)=colnames(cosmic_signatures_v2)
  ref_sigs_present=names(sort(sig_order[ref_sigs_present]))
  
  #Fit signature using mutation counts and reference signatures identified
  if(!file.exists(paste0(filedir,patient,"_restricted.rda"))){
    fit=fit_signatures(counts=counts_patient,signatures = final_sigs_reference_new[ref_sigs_present,],
                       iter = 20000,warmup = 10000,model="poisson",chains = 2)
    pars <- retrieve_pars(fit,par = "exposures",hpd_prob = 0.95)
    saveRDS(pars,paste0(filedir,patient,"_restricted.rda"))}
  pars=readRDS(paste0(filedir,patient,"_restricted.rda"))
  tree = read.tree(paste0(patient,"_snp_tree_with_branch_length.tree"))
  tree_df=fortify(tree)
  cols=all_cols[ref_sigs_present]
  exposures=t(pars$mean[,ref_sigs_present])
  samples=colnames(exposures)[grepl(patient,colnames(exposures))]
  branches=substr(samples,9,nchar(samples))
  
  #Rename branches to remove any text
  branches <- gsub("_branch_snp", "", branches )
  
  
  
  #SBS phylogenetic tree with stacked barplots showing the absolute branch length and contribution of each signature to each branch
  height=6
  pdf(paste0(patient, "_tree_with_ref_signatures_noLegend_restricted_", plotsuffix, "_.pdf"),width=height,height=height)
  plot(tree,label.offset=0.01*max(tree_df$x),show.tip.label=F)
  for (k in 1:length(samples)){
    n=as.numeric(branches[k])
    x_end=tree_df$x[n]
    x_start=tree_df$x[tree_df$parent[n]]
    x_intv=x_end-x_start
    y=node.height(tree)[n]
    tipnum=sum(tree_df$isTip)
    for (s in ref_sigs_present){
      x_end=x_start+exposures[s,samples[k]]*x_intv
      rect(ybottom=y-min(0.02*tipnum,0.4),ytop=y+min(0.02*tipnum,0.4),xleft=x_start,xright=x_end,col=cols[s],lwd=0.5)
      x_start=x_end
    }
  }
  axisPhylo(side = 1,backward=F)
  dev.off()
  print(patient)
}





